<?php
namespace WojciechM\KramBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WojciechM\KramBundle\Entity\Payment;
use WojciechM\KramBundle\Entity\PaymentType;

/**
 * PaymentRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository {
	public function findTotal() {
		return $this->getEntityManager()->createQuery("SELECT SUM(p.amount)
			FROM WojciechMKramBundle:Payment p JOIN p.type pt WHERE pt.name IN(:types)")
			->setParameter("types", array(PaymentType::TYPE_REGULAR, PaymentType::TYPE_EXPENSE))
			->getSingleScalarResult();
	}
}
