<?php
namespace WojciechM\KramBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WojciechM\KramBundle\Entity\Week;

/**
 * WeekRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekRepository extends EntityRepository {

	public function findCurrent() {
		$em = $this->getEntityManager();
		$day = date('N')-1;
		$start = new \DateTime(date('Y-m-d', strtotime('-'.$day.' days')));
		$end = new \DateTime(date('Y-m-d', strtotime('+'.(6-$day).' days')));
		$query = $em
			->createQuery('SELECT w FROM WojciechMKramBundle:Week w ' .
				'WHERE w.start = :start and w.end = :end')
			->setParameter("start", $start)
			->setParameter("end", $end);
		try { 
			$entity = $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $ex) {
			$entity = new Week();
			$entity->setStart($start);
			$entity->setEnd($end);
			$entity->setFee($this->getLastFee());
			$em->persist($entity);
			$em->flush();
		}
		return $entity;
	}
	
	private function getLastFee() {
		$entity = $this->getEntityManager()
			->createQuery("SELECT w FROM WojciechMKramBundle:Week w ORDER BY w.id")
			->getOneOrNullResult();
		return $entity ? $entity->getFee() : 0;
	}

}