security:
    encoders:
        WojciechM\KramBundle\Entity\User:
            algorithm: sha512

    role_hierarchy:
        ROLE_USER: ~
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: WojciechMKramBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            security: true
            anonymous: false
            form_login: ~
            logout:
                path:   /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/0/show, roles: ROLE_USER }
        - { path: ^/user/, roles: ROLE_ADMIN }