payment_type:
    path:     /
    defaults: { _controller: "WojciechMKramBundle:PaymentType:index" }

payment_type_show:
    path:     /{id}/show
    defaults: { _controller: "WojciechMKramBundle:PaymentType:show" }

payment_type_new:
    path:     /new
    defaults: { _controller: "WojciechMKramBundle:PaymentType:new" }

payment_type_create:
    path:     /create
    defaults: { _controller: "WojciechMKramBundle:PaymentType:create" }
    requirements: { _method: post }

payment_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "WojciechMKramBundle:PaymentType:edit" }

payment_type_update:
    path:     /{id}/update
    defaults: { _controller: "WojciechMKramBundle:PaymentType:update" }
    requirements: { _method: post|put }

payment_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "WojciechMKramBundle:PaymentType:delete" }
    requirements: { _method: post|delete }
