shoppinglist:
    path:     /
    defaults: { _controller: "WojciechMKramBundle:ShoppingList:index" }

shoppinglist_show:
    path:     /{id}/show
    defaults: { _controller: "WojciechMKramBundle:ShoppingList:show" }
    
shoppinglist_delete:
    path:     /{id}/delete
    defaults: { _controller: "WojciechMKramBundle:ShoppingList:delete" }
    requirements: { _method: post|delete }
