wojciech_m_kram_homepage:
    path:     /
    defaults: { _controller: WojciechMKramBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: WojciechMKramBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

WojciechMKramBundle_user:
        resource: "@WojciechMKramBundle/Resources/config/routing/user.yml"
        prefix:   /user

WojciechMKramBundle_payment_type:
        resource: "@WojciechMKramBundle/Resources/config/routing/paymenttype.yml"
        prefix:   /payment/type

WojciechMKramBundle_payment_entry:
        resource: "@WojciechMKramBundle/Resources/config/routing/payment.yml"
        prefix:   /payment/entry

WojciechMKramBundle_expense:
        resource: "@WojciechMKramBundle/Resources/config/routing/expense.yml"
        prefix:   /expense

WojciechMKramBundle_week:
        resource: "@WojciechMKramBundle/Resources/config/routing/week.yml"
        prefix:   /week

WojciechMKramBundle_debt:
        resource: "@WojciechMKramBundle/Resources/config/routing/debt.yml"
        prefix:   /debt

WojciechMKramBundle_shoppinglist:
        resource: "@WojciechMKramBundle/Resources/config/routing/shoppinglist.yml"
        prefix:   /shopping
